# Generated by Django 3.1.7 on 2022-08-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood_bank_management_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blood',
            table='students_blood_data',
        ),
    ]
